# Generated by Django 4.1.5 on 2023-01-30 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataCreation", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tank", "Танки"),
                            ("heal", "Хилы"),
                            ("dd", "ДД"),
                            ("buyers", "Торговцы"),
                            ("gildemaster", "Гилдмастеры"),
                            ("quest", "Квестгиверы"),
                            ("smith", "Кузнецы"),
                            ("tanner", "Кожевники"),
                            ("potion", "Зельевары"),
                            ("spellmaster", "Мастера заклинаний"),
                        ],
                        default="tank",
                        max_length=11,
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("upload", models.FileField(upload_to="uploads/")),
            ],
        ),
        migrations.CreateModel(
            name="UserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("status", models.BooleanField(default=False)),
                ("dataCreation", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="board.article"
                    ),
                ),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating_user", models.SmallIntegerField(default=0)),
                (
                    "authorUser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="board.author"
            ),
        ),
    ]
